### PR TITLE
XMLSerializer option to preserve key order

### PR DESCRIPTION
**Pull request by DiscountDarcy**
Make sorting XML keys optional (default true)
Add test
Enable BookTransformer to work either way

### CODE REVIEW

**Comment by DiscountDarcy** [comment]
The build failures seem related to CI pipeline problems (Lucee 4.5 @ ACF 2016) and prior incompatibility with ACF10 (use of **.each()**)

**Comment by elpete** [comment]
Are you based off of the latest master?  I don't think we're using member functions anymore.

**Comment by DiscountDarcy** [comment]
It's based off the last master commit on 12/7/17 by Jon, v6.1.2. Having said that, I don't see any usage of **.each()** anywhere in the repo, so I'm not sure where the runner is hitting it. I didn't use any member functions. Could it possibly be the version of testbox Travis is using?

**Comment by elpete** [comment]
Looks good.  Can you please add a snippet in the README about this option?

**Comment by elpete** [comment]
Thanks so much!

**Pull request merged**
